import json
import math
import os
import zarr
import numpy as np
import glob
from tqdm import tqdm
from strictfire import StrictFire
from typing import List
import multiprocessing
from functools import partial


def split(
    ep_index_path: str,
    num_machines: int,
    output_dir: str,
    existing_completed_eps: str = None,
):
    """
    Split the dataset generation across multiple machines.

    Args:
        ep_index_path: Path to the ep_index.json file.
        num_machines: Number of machines to split the workload across.
        output_dir: Directory to output the completed_eps_N.txt files.
        existing_completed_eps: Optional path to an existing completed_eps.txt file.
            If provided, these episodes will be filtered out before splitting, and
            added to all generated mask files so machines skip them.
    """
    with open(ep_index_path, "r") as f:
        all_episodes = json.load(f)

    completed_set = set()
    if existing_completed_eps is not None:
        if not os.path.exists(existing_completed_eps):
            raise FileNotFoundError(f"Error: {existing_completed_eps} does not exist.")
        with open(existing_completed_eps, "r") as f:
            completed_set = set(line.strip() for line in f if line.strip())

    # Filter out completed episodes
    episodes = []
    for ep in all_episodes:
        scene_id = ep["scene_id"].split("/")[-2]
        ep_id = f"{scene_id}_{ep['episode_id']}_{ep['object_category']}"
        if ep_id not in completed_set:
            episodes.append(ep)

    total_eps = len(episodes)
    if total_eps == 0:
        print("All episodes have already been completed!")
        return

    chunk_size = math.ceil(total_eps / num_machines)

    os.makedirs(output_dir, exist_ok=True)

    machine_assignments = []
    for i in range(num_machines):
        start_idx = i * chunk_size
        end_idx = min((i + 1) * chunk_size, total_eps)
        machine_assignments.append(episodes[start_idx:end_idx])

    for i in range(num_machines):
        completed_eps_file = os.path.join(output_dir, f"completed_eps_{i}.txt")
        with open(completed_eps_file, "w") as f:
            # First write the already completed episodes so this machine skips them
            for ep_id in completed_set:
                f.write(f"{ep_id}\n")

            # Then write the remaining episodes assigned to OTHER machines
            for j in range(num_machines):
                if i == j:
                    continue  # Skip the episodes assigned to this machine
                for ep in machine_assignments[j]:
                    scene_id = ep["scene_id"].split("/")[-2]
                    ep_id = f"{scene_id}_{ep['episode_id']}_{ep['object_category']}"
                    f.write(f"{ep_id}\n")
    print(f"Created {num_machines} completed_eps_*.txt files in {output_dir}")


def _merge_key_task(
    key: str,
    output_dir: str,
    input_zarr_dirs: List[str],
    episode_info: List[dict]
):
    """
    Worker function to merge a single key across all episodes.
    """
    out_zarr = zarr.open(output_dir, mode="a")
    out_data = out_zarr["data"]

    machine_zarrs = []
    for d in input_zarr_dirs:
        z = zarr.open(d, mode="r")
        machine_zarrs.append(z["data"])

    zero_data_episodes = []

    # Try to extract an identity for the tqdm position so progress bars don't overlap too much
    proc = multiprocessing.current_process()
    pos = proc._identity[0] % 8 if proc._identity else 0

    for info in tqdm(episode_info, desc=f"Merging {key}", position=pos, leave=False):
        owner = info["owner"]
        row = info["row"]
        length = info["length"]
        ep_id = info["ep_id"]

        data_slice = machine_zarrs[owner][key][row : row + length]

        # Check if all zeros to catch missing data silently failing
        if not np.any(data_slice):
            zero_data_episodes.append(ep_id)

        out_data[key][row : row + length] = data_slice

    return key, zero_data_episodes


def merge(
    ep_index_path: str,
    output_dir: str,
    *input_zarr_dirs: str,
    completed_eps_files: List[str] = None,
    keys_to_merge: List[str] = None,
    num_workers: int = None,
):
    """
    Merge the generated zarr arrays from multiple machines in parallel.

    Args:
        ep_index_path: Path to the ep_index.json file.
        output_dir: Path to the output merged directory.
        input_zarr_dirs: List of paths to the input zarr directories generated by
            each machine. Supports standard shell wildcard/glob expansion or direct
            wildcard strings (e.g. '../data/zarr/round_2_subset*').
        completed_eps_files: List of paths to the completed_eps.txt files actually
            generated by each machine. If not provided, defaults to finding
            'completed_eps.txt' inside each of the input_zarr_dirs.
        keys_to_merge: Optional list of keys to filter merging.
        num_workers: Number of concurrent workers for parallel merging.
    """
    if not input_zarr_dirs:
        raise ValueError("Must provide at least one input zarr directory.")

    # Expand any glob patterns in input_zarr_dirs
    expanded_dirs = []
    for d in input_zarr_dirs:
        matched = glob.glob(d)
        if not matched:
            expanded_dirs.append(d)
        else:
            expanded_dirs.extend(matched)
    input_zarr_dirs = sorted(expanded_dirs)

    if completed_eps_files is None:
        completed_eps_files = [
            os.path.join(d, "completed_eps.txt") for d in input_zarr_dirs
        ]

    if len(input_zarr_dirs) != len(completed_eps_files):
        raise ValueError(
            "Number of input zarr directories must match number of completed_eps files"
        )

    with open(ep_index_path, "r") as f:
        episodes = json.load(f)

    # Calculate rows for each episode
    lengths = [ep["length"] for ep in episodes]
    cumulative_lengths = np.cumsum([0, *lengths])

    episode_index = {
        (ep["scene_id"].split("/")[-2], str(ep["episode_id"]), ep["object_category"]): (
            row,
            ep["length"],
        )
        for ep, row in zip(episodes, cumulative_lengths)
    }

    # Identify which machine actually completed which episodes
    machine_completed_eps = []
    for file_path in completed_eps_files:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Error: {file_path} does not exist.")

        with open(file_path, "r") as f:
            machine_completed_eps.append(
                set(line.strip() for line in f if line.strip())
            )

    out_zarr = zarr.open(output_dir, mode="w")
    out_data = out_zarr.create_group("data")

    machine_zarrs = []
    for d in input_zarr_dirs:
        try:
            z = zarr.open(d, mode="r")
            if "data" not in z:
                raise ValueError(
                    f"Input zarr directory {d} is missing the 'data' group."
                )
            if len(list(z["data"].keys())) == 0:
                raise ValueError(f"Input zarr directory {d} has an empty 'data' group.")
            machine_zarrs.append(z["data"])
        except Exception as e:
            raise ValueError(f"Failed to open input zarr directory {d}: {e}")

    valid_zarr = machine_zarrs[0]

    expected_total_length = cumulative_lengths[-1]
    keys = list(valid_zarr.keys())

    if keys_to_merge is not None:
        invalid_keys = [k for k in keys_to_merge if k not in keys]
        if invalid_keys:
            raise ValueError(f"Requested keys not found in source Zarr: {invalid_keys}")
        keys = keys_to_merge

    # Create empty datasets for all keys first so workers can write to them
    for key in keys:
        dataset = valid_zarr[key]
        if dataset.shape[0] != expected_total_length:
            raise ValueError(
                f"Dataset shape mismatch! The ep_index.json implies a total length of "
                f"{expected_total_length}, but the input zarr array '{key}' has length "
                f"{dataset.shape[0]}. You must use the EXACT same ep_index.json "
                f"for merging as was used during generation."
            )
        out_data.create_dataset(
            key,
            shape=dataset.shape,
            chunks=dataset.chunks,
            dtype=dataset.dtype,
        )

    # Pre-resolve which machine completed which episode and build workload for workers
    missing_episodes = []
    episode_info = []

    for ep in episodes:
        scene_id = ep["scene_id"].split("/")[-2]
        ep_id = f"{scene_id}_{ep['episode_id']}_{ep['object_category']}"

        owner = None
        for i, machine_completed in enumerate(machine_completed_eps):
            if ep_id in machine_completed:
                if owner is not None:
                    print(
                        f"Warning: episode {ep_id} completed by multiple machines"
                        f" ({owner} and {i}). Using {owner}."
                    )
                else:
                    owner = i

        if owner is None:
            missing_episodes.append(ep_id)
            print(f"Warning: episode {ep_id} not completed by any machine.")
            continue

        row, length = episode_index[
            (scene_id, str(ep["episode_id"]), ep["object_category"])
        ]

        episode_info.append({
            "owner": owner,
            "row": row,
            "length": length,
            "ep_id": ep_id
        })

    if not episode_info:
        raise ValueError("No valid episodes found to merge!")

    if num_workers is None:
        # Default to max 8 workers or number of keys, to avoid hammering disk too hard
        num_workers = min(multiprocessing.cpu_count(), len(keys), 8)
        
    print(f"Merging {len(keys)} keys using {num_workers} parallel workers...")

    zero_data_episodes = []

    worker_fn = partial(
        _merge_key_task,
        output_dir=output_dir,
        input_zarr_dirs=input_zarr_dirs,
        episode_info=episode_info
    )

    with multiprocessing.Pool(processes=num_workers) as pool:
        for key, z_eps in pool.imap_unordered(worker_fn, keys):
            print(f"Finished merging key: {key}")
            zero_data_episodes.extend(z_eps)

    if missing_episodes or zero_data_episodes:
        error_msg = "Merging completed, but with warnings about missing/zero data.\n"
        if missing_episodes:
            error_msg += (
                f"Missing episodes ({len(missing_episodes)} total): "
                f"{missing_episodes}\n"
            )
        if zero_data_episodes:
            error_msg += (
                f"Zero-data episodes ({len(set(zero_data_episodes))} total): "
                f"{list(set(zero_data_episodes))}\n"
            )
        print(f"WARNING: {error_msg}")

    print(f"Successfully merged {len(input_zarr_dirs)} zarr arrays into {output_dir}")


if __name__ == "__main__":
    multiprocessing.set_start_method("spawn", force=True)
    StrictFire({"split": split, "merge": merge})
